### ISSUE TITLE
Bug: MediaPlayer integration URI error

### ISSUE THREAD

**Issue by miit86** [LAB02-Research/HASS.Agent-MediaPlayer#1]
Hi,

I Get below Error:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hass_agent_mediaplayer/media_player.py", line 119, in update
    self._volumeLevel = int(response.text)
ValueError: invalid literal for int() with base 10: 'Method Not Implemented: Get /media'
```
HA version: 22.5.3
Hass Agent version: 2022.11.4

**Comment by lbandi2** [comment]
I get the same thing.

**Comment by TheHolyRoger** [comment]
Same thing :)

**Comment by Famku** [comment]
dito

**Comment by Davorin1994** [comment]
I have the same issue, here are my logs below :( 

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/hass_agent_mediaplayer/media_player.py:119
Integration: hass_agent_mediaplayer (documentation, issues)
First occurred: 6:14:41 PM (1 occurrences)
Last logged: 6:14:41 PM

Update for media_player.windows11_mediaplayer fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hass_agent_mediaplayer/media_player.py", line 119, in update
    self._volumeLevel = int(response.text)
ValueError: invalid literal for int() with base 10: 'Method Not Implemented: Get /media'

**Comment by Davorin1994** [comment]
> I have the same issue, here are my logs below :(
> 
> This error originated from a custom integration.
> 
> Logger: homeassistant.helpers.entity Source: custom_components/hass_agent_mediaplayer/media_player.py:119 Integration: hass_agent_mediaplayer (documentation, issues) First occurred: 6:14:41 PM (1 occurrences) Last logged: 6:14:41 PM
> 
> Update for media_player.windows11_mediaplayer fails Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state await self.async_device_update() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update raise exc File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/hass_agent_mediaplayer/media_player.py", line 119, in update self._volumeLevel = int(response.text) ValueError: invalid literal for int() with base 10: 'Method Not Implemented: Get /media'

SYSTEM INFO:

Home Assistant Core 2022.7.0.dev20220604
Home Assistant Supervisor 2022.05.3
Home Assistant OS 9.0.dev20220601
Hass Agent version: 2022.11.4

**Comment by LAB02-Admin** [comment]
Wow I have not been receiving any notifications for this issue! Sorry you've been waiting so long, no idea why either ☹️ 

Can you please post your media_player entity yaml here?


Edit: Apparently I wasn't 'following' this project, which I assumed always happens when you create it. Enabled now.

**Comment by LAB02-Admin** [comment]
Did all of you install the latest beta by the way? Because the stable release doesn't contain the mediaplayer component yet.

https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.12.0-beta4

**Comment by lbandi2** [comment]
> Did all of you install the latest beta by the way? Because the stable release doesn't contain the mediaplayer component yet.
> 
> https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.12.0-beta4

That beta did it for me. Works perfectly now, thanks!

**Comment by Famku** [comment]
Works with 2022.12.0-beta4

Thanks

**Comment by LAB02-Admin** [comment]
Alright we'll I'm closing this, if anyone still has problems despite the beta let me know!
