### ISSUE TITLE
Errors on Installing HASS.Agent-MediaPlayer

### ISSUE THREAD

**Issue by labrunning** [LAB02-Research/HASS.Agent-MediaPlayer#2]
I am experiencing errors on the first install of HASS.Agent-MediaPlayer. I installed from HACS, release 2022.5.7. I have the main HASS.Agent installed and working fine, and if I visit the http://{hass-agent-ip}:5115 I get "HASS.Agent Active". I don't see the media player listed.

Please let me know if you need any more information.

## HASS

Version | core-2022.6.7
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.12
Operating System Family | Linux
Operating System Version | 5.15.32-v8
CPU Architecture | aarch64
Timezone | Europe/London

## Log Output

Logger: homeassistant.util.logging
Source: util/logging.py:116
First occurred: 13:10:55 (20 occurrences)
Last logged: 13:14:53

Exception in message_received when handling msg on 'homeassistant/sensor/MOTHER/MOTHER_audio/MOTHER_audio_audio_sessions/state': '[ { "Application": "svchost", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "obs64", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "Teams", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 14.685059 }, { "Application": "Teams", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 7.8774533 }, { "Application": "svchost", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "obs64", "Muted": false, "MasterVolume": 85.106384, "PeakVolume": 6.7042155 } ]' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 47, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 304, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 680, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1429, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1097, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.mother_audio_audio_sessions. State max length is 255 characters.
Exception in message_received when handling msg on 'homeassistant/sensor/MOTHER/MOTHER_audio/MOTHER_audio_audio_sessions/state': '[ { "Application": "svchost", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "obs64", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "Teams", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 35.577393 }, { "Application": "Teams", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 19.084654 }, { "Application": "svchost", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "obs64", "Muted": false, "MasterVolume": 85.106384, "PeakVolume": 16.242258 } ]' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 47, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 304, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 680, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1429, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1097, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.mother_audio_audio_sessions. State max length is 255 characters.
Exception in message_received when handling msg on 'homeassistant/sensor/MOTHER/MOTHER_audio/MOTHER_audio_audio_sessions/state': '[ { "Application": "svchost", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "obs64", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "Teams", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 52.62146 }, { "Application": "Teams", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 28.227541 }, { "Application": "svchost", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "obs64", "Muted": false, "MasterVolume": 85.106384, "PeakVolume": 24.02344 } ]' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 47, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 304, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 680, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1429, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1097, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.mother_audio_audio_sessions. State max length is 255 characters.
Exception in message_received when handling msg on 'homeassistant/sensor/MOTHER/MOTHER_audio/MOTHER_audio_audio_sessions/state': '[ { "Application": "svchost", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "obs64", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "Teams", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 43.59436 }, { "Application": "Teams", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 23.385166 }, { "Application": "svchost", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "obs64", "Muted": false, "MasterVolume": 85.106384, "PeakVolume": 19.902271 } ]' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 47, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 304, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 680, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1429, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1097, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.mother_audio_audio_sessions. State max length is 255 characters.
Exception in availability_message_received when handling msg on 'homeassistant/sensor/MOTHER/availability': 'online' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 47, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 517, in availability_message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 680, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1429, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1097, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.mother_audio_audio_sessions. State max length is 255 characters.

**Comment by LAB02-Admin** [comment]
Could you please show me your yaml configuration for the media_player entity?

**Comment by labrunning** [comment]
I use `media_player: !include_dir_merge_named entities/media_players` in cofiguration.yaml so had to slightly adjust my media player entry. I'm using this for reference;

```
---
platform: hass_agent_mediaplayer
name: "mother"
host: 192.168.1.100
port: 5115
```

I've now got the media player to appear, but I get 'unavailable' and this in the logs;

Logger: homeassistant.util.logging
Source: util/logging.py:116
First occurred: 14:44:37 (22 occurrences)
Last logged: 14:48:48

Exception in message_received when handling msg on 'homeassistant/sensor/MOTHER/MOTHER_audio/MOTHER_audio_audio_sessions/state': '[ { "Application": "svchost", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "obs64", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "svchost", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "iTunes", "Muted": false, "MasterVolume": 85.106384, "PeakVolume": 16.403255 }, { "Application": "obs64", "Muted": false, "MasterVolume": 85.106384, "PeakVolume": 6.373302 } ]' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 47, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 304, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 680, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1429, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1097, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.mother_audio_audio_sessions. State max length is 255 characters.
Exception in message_received when handling msg on 'homeassistant/sensor/MOTHER/MOTHER_audio/MOTHER_audio_audio_sessions/state': '[ { "Application": "svchost", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "obs64", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "svchost", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "iTunes", "Muted": false, "MasterVolume": 85.106384, "PeakVolume": 20.49433 }, { "Application": "obs64", "Muted": false, "MasterVolume": 85.106384, "PeakVolume": 7.962843 } ]' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 47, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 304, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 680, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1429, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1097, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.mother_audio_audio_sessions. State max length is 255 characters.
Exception in message_received when handling msg on 'homeassistant/sensor/MOTHER/MOTHER_audio/MOTHER_audio_audio_sessions/state': '[ { "Application": "svchost", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "obs64", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "svchost", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "iTunes", "Muted": false, "MasterVolume": 85.106384, "PeakVolume": 12.063508 }, { "Application": "obs64", "Muted": false, "MasterVolume": 85.106384, "PeakVolume": 4.6871414 } ]' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 47, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 304, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 680, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1429, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1097, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.mother_audio_audio_sessions. State max length is 255 characters.
Exception in message_received when handling msg on 'homeassistant/sensor/MOTHER/MOTHER_audio/MOTHER_audio_audio_sessions/state': '[ { "Application": "svchost", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "obs64", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "svchost", "Muted": false, "MasterVolume": 100.0, "PeakVolume": 0.0 }, { "Application": "iTunes", "Muted": false, "MasterVolume": 85.106384, "PeakVolume": 12.770815 }, { "Application": "obs64", "Muted": false, "MasterVolume": 85.106384, "PeakVolume": 4.961958 } ]' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 47, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 304, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 680, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1429, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1097, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.mother_audio_audio_sessions. State max length is 255 characters.
Exception in availability_message_received when handling msg on 'homeassistant/sensor/MOTHER/availability': 'online' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 47, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 517, in availability_message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 680, in _async_write_ha_state self.hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1429, in async_set state = State( File "/usr/src/homeassistant/homeassistant/core.py", line 1097, in __init__ raise InvalidStateError( homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.mother_audio_audio_sessions. State max length is 255 characters.

**Comment by LAB02-Admin** [comment]
Those logs are for hass.agent sensors, namely the audio sensor - it's a known bug, when your audio sessions take more than 255 chars, it gets dropped. But doesn't matter for the media_player addon.

Could you please enable this in Configuration.yaml:

```yaml
logger:
  default: warning
  logs:
    custom_components.hass_agent_mediaplayer: debug
```

Then restart HA. I use the 'Log Viewer' addon, who should then show you something like this:

![log](https://raw.githubusercontent.com/LAB02-Research/HASS.Agent/main/images/mediaplayer_debug_logging.png)

**Comment by labrunning** [comment]
Thanks for your help with this. I came to HASS.Agent via Smart Home Solver on YouTube so just installed. However I have two accounts on my computer, a work one and a personal one and of course I am going to want to run it across both those accounts. Having caught up on the forum posts a bit I see that I should probably go for the zip installation method. I'll give that a try. FYI, this is the post I'm going to follow; https://community.home-assistant.io/t/hass-agent-windows-client-to-receive-notifications-use-commands-sensors-quick-actions-and-more/369094/85?u=reclusivemonkey

**Comment by LAB02-Admin** [comment]
Hey @labrunning,

What I'd suggest is running the installer on one account, say your personal one. That way, the satellite service gets installed as well, etc. 

Then for acct. number two, just [take the zip package](https://github.com/LAB02-Research/HASS.Agent/releases/latest/download/HASS.Agent.zip) and extract it anywhere (with read/write rights, so not programfiles). To make it easy, you can copy `appsettings.json` from the other account (it's in the `config` subfolder). Don't copy the commands/quickactions/sensors files, that'll break things.

Configure any sensor that you always want running (regardless of which user you're using) in the satellite service.

Remember to open Configuration -> Startup and click `enable start-on-login`.
